### ISSUE TITLE
Springboot1.4 并没有解决依赖循环的问题

### ISSUE THREAD

**Issue by zowbman** [ggj2010/javabase#2]
https://github.com/ggj2010/javabase/blob/b113fc8e0c54ae725e93ab1349e980038be1d8ee/mobiletechnology/src/main/java/com/ggj/encrypt/common/utils/mybatis/MyAbstractRoutingDataSource.java
在配置数据源roundRobinDataSouceProxy()方法不需要声明bean，使用proxy.afterPropertiesSet();就好了

**Comment by ggj2010** [comment]
没有理解你这句话的意思哦  “”在配置数据源roundRobinDataSouceProxy()方法不需要声明bean，使用proxy.afterPropertiesSet();就好了“”
关于 Springboot1.4 并没有解决依赖循环的问题。
是因为   算是spring1.4.0的一个bug  你看下这个类DataSourceProperties提交记录备注就知道了

**Comment by zowbman** [comment]
先回答你close掉的那个问题吧，SpringContextHolder类实现了ApplicationContextAware，获取applicationContext，会比带注解@Configuration的类执行慢，我这边是这样子

第二个问题：请看看我的代码https://github.com/zowbman/zh_rms/blob/master/src/main/java/com/rms/config/readwriteseparation/datasource/DataSourceConfig.java

roundRobinDataSouceProxy()方法并没有使用注解@bean声明，因为如果使用@bean注解声明此方法，在方法内获取dataSource会出现循环依赖的问题

**Comment by zowbman** [comment]
我入坑java 一年了，并且大概浏览了你的github，很不错里面的知识，希望向你学习

**Comment by ggj2010** [comment]
相互学习！
